### ISSUE TITLE
Appending form Data to Body of request

### ISSUE THREAD

**Issue by mlasy** [Vydia/ReactNativeBackgroundUploadExample#6]
Hey, 

thanks for the great work so far, it helped me a lot. uploading a big file works like charm.
However, i still dont know how to append form data to the body of the request.
This is the analog **working request** in plain HTML

```
<form action="/api/video" method="POST" enctype="multipart/form-data" class="padding">
      <input type="text" name="height" ><br>
      <input type="file" name="video">
      <input type="submit" value="Abschicken">
 </form> 

```
which returns the following on the node.js server
```
body: {height: '186'},
  files: 
   { video: 
      { data: <Buffer 00 00 00 18 66 74 79 70 6d 70 34 32 00 00 00 00 69 73 6f 6d 6d 70 34 32 00 00 06 b2 6d 6f 6f 76 00 00 00 6c 6d 76 68 64 00 00 00 00 d6 4d 4b f7 d6 4d ... >,
        name: 'VID_20171206_082540.mp4',
        encoding: '7bit',
        mimetype: 'video/mp4',
        truncated: false,
        size: 3649840 } },
```

However, this is the relevant react native code from my current Upload.js (i added "height" to options), i am desperate to get it to work:

```

onPress={() => this.onPressUpload({
              url: 'http://localhost:3000/api/video',
              field: 'video',
              type: 'multipart'
            })
}

startUpload = (opts) => {
    console.log("opts", opts);

    Upload.getFileInfo(opts.path).then((metadata) => {
      const options = Object.assign({
        method: 'POST',
        headers: {
          'content-type': metadata.mimeType // server requires a content-type header
        },
        body: JSON.stringify({
          weight:opts["height"],
        })
      }, opts)
    
      Upload.startUpload(options).then((uploadId) => {
        console.log(`Upload started with options: ${JSON.stringify(options)}`)
        Upload.addListener('progress', uploadId, (data) => {
          console.log(`Progress: ${data.progress}%`)
        })
        Upload.addListener('error', uploadId, (data) => {
          console.log(`Error: ${data.error}%`)
        })
        Upload.addListener('completed', uploadId, (data) => {
          console.log('Completed!')
        })
      }).catch(function(err) {
        console.log('Upload error!', err)
      })
    })
  }
```

it returns 
```
body: {},
  files: 
   { video: 
      { data: <Buffer 00 00 00 18 66 74 79 70 6d 70 34 32 00 00 00 00 69 73 6f 6d 6d 70 34 32 00 00 06 b2 6d 6f 6f 76 00 00 00 6c 6d 76 68 64 00 00 00 00 d6 4d 4b f7 d6 4d ... >,
        name: 'VID_20171206_082540.mp4',
        encoding: '7bit',
        mimetype: 'video/mp4',
        truncated: false,
        size: 3649840 } },
```

**Comment by TSMMark** [comment]
Sorry, I think you have to use an HTTP header currently. Feel free to try this branch: https://github.com/Vydia/react-native-background-upload/pull/46

If it works for you and you would like to see it released, submit a PR to https://github.com/Vydia/ReactNativeBackgroundUploadExample which utilizes the feature so that we can test it, merge it, and release it.

**Comment by TSMMark** [comment]
Closing this as form parameters are supported as of [v4.4.0](https://github.com/Vydia/react-native-background-upload/releases/tag/v4.4.0)

**Comment by Zabi-Progton** [comment]
Unable to add data[type]='answer' and data[video]='uriToVideo', in upload request, can someone please write down the syntax for that, Because this is giving me errors: 

 const options = {
      url: `${JENGA_APP}hap_quest/new`,
      path: Platform.OS === 'ios' ? uri : uri.substring(7),
      method: 'POST',
      type: 'multipart',

      customUploadId: `video${id}`,
      headers: {
        'content-type': 'application/octet-stream', // Customize content-type
      },

      field: 'type', //Is this correct way for this
      // Below are options only supported on Android and are must for Oreo and above
      notification: {
        enabled: true,
        notificationChannel: 'Survey video upload',
      },
    };
